//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnugglyStuffWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public string OrderedImage { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
